import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/ui/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`bg-bg text-text ${inter.className}`}>
        <Navbar />
        <section className='sm:mt-16 md:mt-16 lg:pt-20 xl:pt-24'>{children}</section>
      </body>
    </html>
  )
}
